# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOsb6cr2HooS_7GMWggdEMn1QdEIR0DH
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
d=pd.read_csv('Titanic-Dataset.csv')
d

d.isnull().sum()

d.drop('Cabin',axis=1,inplace=True)
d

d[d['Embarked'].isnull()]

df=d[~d['Embarked'].isnull()]
df

df.isnull().sum()



x=df[df['Age'].isnull()]
y=df[~df['Age'].isnull()]

x

y

df.groupby('Pclass')['Age'].mean()

def ad(x):
  if x==1:
    return 38
  elif x==2:
    return 29
  else:
    return 25

x['Age']=x['Pclass'].apply(ad)

x

final=pd.concat((x,y),ignore_index=True)
final

final.isnull().sum()

final.to_csv('cleaned_data.csv', index=False)
files.download('cleaned_data.csv')

final

import matplotlib.pyplot as plt
import seaborn as sns



survival_counts = final['Survived'].value_counts()
plt.pie(survival_counts,
        labels=['Not Survived', 'Survived'],
        autopct='%1.0f%%',
        startangle=90,
        explode=[0.1,0])
plt.title("Survival Distribution")
plt.show()

plt.hist(final['Age'], bins=10, color='skyblue', edgecolor='black')
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

sns.countplot(data=final, x='Sex', hue='Survived')
plt.title("Survival by Gender")
plt.show()

sns.countplot(x="Embarked", hue="Survived", data=final)
plt.title("Survival by Embarked Port")
plt.show()

sns.histplot(data=final, x="Age", hue="Sex", bins=30, kde=True)
plt.title("Age Distribution by Gender")
plt.show()

