# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9SrNdzSjuGICuDnEBhfMMjZLagtVhxM
"""

from google.colab import files
uploaded=files.upload()

!pip install pandas
import pandas as pd
d=pd.read_csv('Titanic-Dataset (1).csv')
d

d.isnull().sum()

d.drop('Cabin',axis=1,inplace=True)

d[d['Embarked'].isnull()]

df=d[~d['Embarked'].isnull()]
df

x=df[df['Age'].isnull()]
y=df[~df['Age'].isnull()]

x

y

df.groupby('Pclass')['Age'].mean()

def ad(x):
  if x==1:
    return 38
  elif x==2:
    return 29
  else:
    return 25

x['Age']=x['Pclass'].apply(ad)

x

final=pd.concat((x,y),ignore_index=True)
final

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
final['Sex']=le.fit_transform(final['Sex'])
final['Embarked']=le.fit_transform(final['Embarked'])

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
final[['Age','Fare']]=scaler.fit_transform(final[['Age','Fare']])

import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(final['Age'])
plt.show()

sns.boxplot(final['Fare'])
plt.show()

Q1=final['Fare'].quantile(0.25)
Q3=final['Fare'].quantile(0.75)
IQR=Q3-Q1

final=final[(final['Fare']>=Q1-1.5*IQR)&(final['Fare']<=Q3+1.5*IQR)]

final



final.to_csv('cleaned_data.csv', index=False)
files.download('cleaned_data.csv')

